# Generated by Django 2.2.14 on 2021-05-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('link_promo', models.URLField(blank=True, null=True, verbose_name='Promoción Url')),
                ('idvideo', models.CharField(max_length=500, verbose_name='Id del Video')),
                ('fecha_subida', models.DateField(blank=True, null=True, verbose_name='Fecha Ejecución')),
                ('hora_subida', models.TimeField(blank=True, null=True, verbose_name='Hora Ejecución')),
                ('visto', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
